"""init db

Revision ID: f80a276d3f4f
Revises: e8985e4b7310
Create Date: 2023-05-26 02:29:47.641740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f80a276d3f4f'
down_revision = 'e8985e4b7310'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('branch', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'branch')
    # ### end Alembic commands ###
